-- New first-class scaffold table
CREATE TABLE scaffold (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR(20) NOT NULL DEFAULT 'NONE'
                     CHECK (status IN ('NONE', 'AVAILABLE', 'IN_USE')),
    start_date   DATE,
    end_date     DATE,
    house_id     INTEGER REFERENCES house(id) ON DELETE SET NULL
);

-- Migrate existing scaffold data from house columns
INSERT INTO scaffold (status, start_date, end_date, house_id)
SELECT scaffold_status, scaffold_start_date, scaffold_end_date, id
FROM house
WHERE scaffold_status != 'NONE'
   OR scaffold_start_date IS NOT NULL
   OR scaffold_end_date   IS NOT NULL;
