-- Rename the worker trade column (was misnamed "crew")
ALTER TABLE worker RENAME COLUMN crew TO trade;

-- Crew entity: a named crew managed by one manager
CREATE TABLE crew (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    manager_id  INTEGER REFERENCES worker(id) ON DELETE SET NULL
);

-- A worker (leader or member) belongs to at most one crew
ALTER TABLE worker ADD COLUMN crew_id INTEGER REFERENCES crew(id) ON DELETE SET NULL;
