-- Fleet tracking fed by GPS.bg (GPSHunter SOAP). See the `gps` package.
--
-- GPS.bg answers one query per 181 s per account, so the browser never talks to it: a single
-- background poller (GpsPoller) writes these tables and every /api/vehicles read is served from them.
--
-- vehicle               one row per GPS unit, discovered from GetStatus("0"). Provider fields
--                       (provider_name, reg_number, last_*) are overwritten on every poll; alias,
--                       notes, active and driver_worker_id are ours and the sync never touches them.
-- vehicle_position      a breadcrumb: one row each time GetStatus reports a new LastTS. GPS.bg exposes
--                       no point-by-point track, so this (one point per poll, ~3-4 min apart) is it.
-- vehicle_route_segment VehicleRoutesList rows: alternating driving and stopped segments. Re-fetching
--                       a window replaces it, so repeated syncs of the same day are idempotent.

CREATE TABLE public.vehicle (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- GPS.bg object code. Text: the provider sends it as a string and it is only ever an id.
    gps_code          varchar(32)  NOT NULL UNIQUE,
    provider_name     varchar(255),
    reg_number        varchar(32),
    alias             varchar(255),
    notes             text,
    -- Inactive vehicles still get live status (GetStatus returns every unit) but no trip syncs.
    active            boolean      NOT NULL DEFAULT true,
    driver_worker_id  integer      REFERENCES public.worker(id) ON DELETE SET NULL,
    last_ts           timestamp with time zone,
    last_lat          double precision,
    last_lng          double precision,
    last_speed_kmh    double precision,
    last_heading      integer,
    ignition          boolean,
    -- GPS.bg IsOnline. Not trustworthy on its own: a unit silent for two days still reports true.
    -- The UI judges staleness from last_ts instead.
    online            boolean,
    last_driver       varchar(255),
    last_address      varchar(500),
    odometer_km       double precision,
    battery_v         double precision,
    ext_power_v       double precision,
    -- The whole GetStatus struct (analog inputs, digital I/O, tachograph...) for the detail view.
    last_status_json  jsonb,
    status_synced_at  timestamp with time zone,
    routes_synced_at  timestamp with time zone,
    created_at        timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.vehicle_position (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id  integer NOT NULL REFERENCES public.vehicle(id) ON DELETE CASCADE,
    ts          timestamp with time zone NOT NULL,
    lat         double precision NOT NULL,
    lng         double precision NOT NULL,
    speed_kmh   double precision,
    heading     integer,
    ignition    boolean,
    -- Also the index for the only read: one vehicle, one time window.
    CONSTRAINT uq_vehicle_position UNIQUE (vehicle_id, ts)
);

CREATE TABLE public.vehicle_route_segment (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id     integer NOT NULL REFERENCES public.vehicle(id) ON DELETE CASCADE,
    -- GPS.bg Ign: true = driving segment, false = stop.
    moving         boolean NOT NULL,
    start_ts       timestamp with time zone NOT NULL,
    end_ts         timestamp with time zone,
    duration_s     integer,
    start_lat      double precision,
    start_lng      double precision,
    end_lat        double precision,
    end_lng        double precision,
    distance_km    double precision,
    avg_speed_kmh  double precision,
    max_speed_kmh  double precision,
    max_accel      double precision,
    max_decel      double precision,
    idle_s         integer,
    -- GPS.bg Fuel_1. An estimate, not a measurement: it is exactly distance x a flat 8 L/100 km.
    fuel_est_l     double precision,
    driver         varchar(255),
    start_place    varchar(255),
    end_place      varchar(255),
    -- Every field of the provider row, including the ones without a column here.
    raw_json       jsonb NOT NULL,
    synced_at      timestamp with time zone NOT NULL DEFAULT now(),
    -- moving is part of the key: a zero-length stop (GPS.bg emits them) could share its start
    -- second with the next drive.
    CONSTRAINT uq_vehicle_route_segment UNIQUE (vehicle_id, start_ts, moving)
);

-- Fleet menu group. Admin only — but that gate lives in SecurityConfig and in index.html
-- (_flApplyRoleGate), not in this table: menu_config only decides visibility and order.
INSERT INTO menu_config (menu_key, section, label_en, label_bg, icon, visible, sort_order, is_group, parent_key) VALUES
  ('nav_group_fleet',    'nav', 'Fleet',    'Автопарк',          '🚚', true, 11, true,  NULL),
  ('nav_fleet_map',      'nav', 'Live Map', 'Карта на живо',     '📍', true, 1,  false, 'nav_group_fleet'),
  ('nav_fleet_vehicles', 'nav', 'Vehicles', 'Превозни средства', '🚐', true, 2,  false, 'nav_group_fleet'),
  ('nav_fleet_trips',    'nav', 'Trips',    'Пътувания',         '🧭', true, 3,  false, 'nav_group_fleet');
