-- Tedhouse logistics schema (PostgreSQL port of teodor-logistica MySQL dump)

CREATE TABLE material (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    unit    VARCHAR(50)  NOT NULL,
    price   NUMERIC(10, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE house (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    location        VARCHAR(255) NOT NULL,
    lat             NUMERIC(9, 6),
    lng             NUMERIC(9, 6),
    start_date      DATE,
    current_phase   VARCHAR(100)
);

CREATE TABLE warehouse (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id  INTEGER NOT NULL UNIQUE,
    CONSTRAINT fk_warehouse_house FOREIGN KEY (house_id) REFERENCES house (id) ON DELETE CASCADE
);

CREATE TABLE inventory (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id  INTEGER NOT NULL,
    material_id   INTEGER NOT NULL,
    quantity      NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT uq_inv UNIQUE (warehouse_id, material_id),
    CONSTRAINT fk_inv_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_material  FOREIGN KEY (material_id)  REFERENCES material  (id) ON DELETE CASCADE
);

CREATE INDEX idx_inv_material ON inventory (material_id);

CREATE TABLE supplier (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(150) NOT NULL,
    location  VARCHAR(255) NOT NULL,
    lat       NUMERIC(9, 6),
    lng       NUMERIC(9, 6)
);

CREATE TABLE driver (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(150) NOT NULL,
    van   VARCHAR(100) NOT NULL
);

-- "users" is reserved in PostgreSQL; use app_user
CREATE TABLE app_user (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(10)  NOT NULL DEFAULT 'user',
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_user_role CHECK (role IN ('admin', 'user'))
);
