-- Tier-2 routing nodes: company-owned warehouses (called "depot" internally to avoid a
-- name clash with the existing `warehouse` table, which is 1:1 plumbing for house stock).
-- A depot stocks several materials; unlike supplier_inventory there is no unit_price since
-- this is owned stock already valued by material.price.

CREATE TABLE depot (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(150) NOT NULL,
    location  VARCHAR(255) NOT NULL,
    lat       NUMERIC(9, 6),
    lng       NUMERIC(9, 6)
);

CREATE TABLE depot_inventory (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depot_id     INTEGER        NOT NULL,
    material_id  INTEGER        NOT NULL,
    quantity     NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT uq_depot_inv UNIQUE (depot_id, material_id),
    CONSTRAINT fk_depot_inv_depot    FOREIGN KEY (depot_id)    REFERENCES depot    (id) ON DELETE CASCADE,
    CONSTRAINT fk_depot_inv_material FOREIGN KEY (material_id) REFERENCES material (id) ON DELETE CASCADE,
    CONSTRAINT chk_depot_inv_quantity CHECK (quantity >= 0)
);

CREATE INDEX idx_depot_inv_material ON depot_inventory (material_id);
