CREATE TABLE house_order (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id    INTEGER NOT NULL REFERENCES house(id) ON DELETE CASCADE,
    status      VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                    CHECK (status IN ('DRAFT','CONFIRMED','DELIVERED','CANCELLED')),
    notes       TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE house_order_item (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER NOT NULL REFERENCES house_order(id) ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES material(id),
    quantity    NUMERIC(10,2) NOT NULL CHECK (quantity > 0),
    UNIQUE (order_id, material_id)
);
