CREATE TABLE delivery (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER NOT NULL REFERENCES house_order(id) ON DELETE CASCADE,
    delivered_at TIMESTAMP NOT NULL DEFAULT NOW(),
    notes       TEXT
);

CREATE TABLE delivery_item (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id     INTEGER NOT NULL REFERENCES delivery(id) ON DELETE CASCADE,
    material_id     INTEGER NOT NULL REFERENCES material(id),
    qty_delivered   NUMERIC(10,2) NOT NULL CHECK (qty_delivered > 0),
    UNIQUE (delivery_id, material_id)
);
