    -- ============================================================
--  V3 — CSV sync state (Google Sheets → DB, recurring)
--
--  Design: DATA_IMPORT_PLAN.md
--
--  Three tables, none of which the business flows touch:
--    import_batch    — one row per import run (the operational record)
--    import_ref      — external_key → our id, PLUS the per-row three-way-merge baseline
--    import_conflict — a column that moved on both sides, kept open across runs
--
--  import_ref is polymorphic and deliberately has NO FK to the mapped entity — same
--  pattern as audit_log's actor columns. A row deleted from the UI leaves a dangling
--  mapping, which the resolver repairs by re-creating the entity for that key.
-- ============================================================

CREATE TABLE public.import_batch (
    id             bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    public_id      uuid        NOT NULL,
    started_at     timestamp with time zone NOT NULL DEFAULT now(),
    finished_at    timestamp with time zone,
    entity_type    character varying(40)  NOT NULL,
    mode           character varying(10)  NOT NULL,
    filename       character varying(255),
    app_user_id    integer,
    username       character varying(255),
    rows_read      integer NOT NULL DEFAULT 0,
    rows_created   integer NOT NULL DEFAULT 0,
    rows_updated   integer NOT NULL DEFAULT 0,
    rows_unchanged integer NOT NULL DEFAULT 0,
    rows_kept_app  integer NOT NULL DEFAULT 0,
    rows_conflict  integer NOT NULL DEFAULT 0,
    rows_failed    integer NOT NULL DEFAULT 0,
    status         character varying(16) NOT NULL,
    report_json    jsonb,
    CONSTRAINT chk_import_batch_mode   CHECK (mode   IN ('validate','apply')),
    CONSTRAINT chk_import_batch_status CHECK (status IN ('running','ok','partial','failed'))
);

CREATE TABLE public.import_ref (
    id              bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type     character varying(40)  NOT NULL,
    external_key    character varying(120) NOT NULL,
    entity_id       bigint       NOT NULL,
    -- Three-way merge state. TWO baselines, not one: after a KEPT_APP the two sides are
    -- deliberately out of sync (the app holds 99, the sheet still says 10), so a single
    -- baseline cannot answer both questions. Collapsing them makes the next run read the
    -- stale sheet as "changed" and overwrite the app value that KEPT_APP just protected.
    --   synced_snapshot — the app-side values as of the last run → "did the app change?"
    --   source_snapshot — the sheet-side values as of the last run → "did the sheet change?"
    -- Values, not just hashes, because the merge is per column and the conflict report shows
    -- base/app/sheet side by side. source_hash is the cheap whole-row fingerprint.
    source_hash     character varying(64),
    synced_snapshot jsonb,
    source_snapshot jsonb,
    last_synced_at  timestamp with time zone,
    last_batch_id   bigint,
    created_at      timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.import_conflict (
    id           bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ref_id       bigint       NOT NULL,
    batch_id     bigint,
    entity_type  character varying(40)  NOT NULL,
    external_key character varying(120) NOT NULL,
    column_name  character varying(64)  NOT NULL,
    base_value   text,
    app_value    text,
    sheet_value  text,
    detected_at  timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at  timestamp with time zone,
    resolution   character varying(16),
    CONSTRAINT chk_import_conflict_resolution CHECK (resolution IN ('sheet','app','manual'))
);


-- ────────────────────────────────────────────────────────────
--  PRIMARY / UNIQUE KEYS
-- ────────────────────────────────────────────────────────────

ALTER TABLE ONLY public.import_batch    ADD CONSTRAINT import_batch_pkey          PRIMARY KEY (id);
ALTER TABLE ONLY public.import_ref      ADD CONSTRAINT import_ref_pkey            PRIMARY KEY (id);
ALTER TABLE ONLY public.import_conflict ADD CONSTRAINT import_conflict_pkey       PRIMARY KEY (id);

ALTER TABLE ONLY public.import_batch    ADD CONSTRAINT import_batch_public_id_key UNIQUE (public_id);
-- The heart of the whole design: one entity per (type, external key), DB-enforced.
ALTER TABLE ONLY public.import_ref      ADD CONSTRAINT uq_import_ref              UNIQUE (entity_type, external_key);


-- ────────────────────────────────────────────────────────────
--  FOREIGN KEYS  (only between the import tables themselves)
-- ────────────────────────────────────────────────────────────

ALTER TABLE ONLY public.import_batch
    ADD CONSTRAINT fk_import_batch_user  FOREIGN KEY (app_user_id)   REFERENCES public.app_user(id)      ON DELETE SET NULL;
ALTER TABLE ONLY public.import_ref
    ADD CONSTRAINT fk_import_ref_batch   FOREIGN KEY (last_batch_id) REFERENCES public.import_batch(id)  ON DELETE SET NULL;
ALTER TABLE ONLY public.import_conflict
    ADD CONSTRAINT fk_conflict_ref       FOREIGN KEY (ref_id)        REFERENCES public.import_ref(id)    ON DELETE CASCADE;
ALTER TABLE ONLY public.import_conflict
    ADD CONSTRAINT fk_conflict_batch     FOREIGN KEY (batch_id)      REFERENCES public.import_batch(id)  ON DELETE SET NULL;


-- ────────────────────────────────────────────────────────────
--  INDEXES
-- ────────────────────────────────────────────────────────────

CREATE INDEX idx_import_batch_at     ON public.import_batch    USING btree (started_at DESC);
CREATE INDEX idx_import_batch_entity ON public.import_batch    USING btree (entity_type, started_at DESC);
-- Reverse lookup: "which external key does this house come from?" (dangling-mapping repair).
CREATE INDEX idx_import_ref_entity   ON public.import_ref      USING btree (entity_type, entity_id);
-- Open conflicts per entity — the /api/import/conflicts listing.
CREATE INDEX idx_conflict_open       ON public.import_conflict USING btree (entity_type, resolved_at);
CREATE INDEX idx_conflict_ref        ON public.import_conflict USING btree (ref_id, column_name);
