-- Phase-5 supplier fallback: a supplier may stock several materials with their own price.
-- supplier and material tables already exist (V1); only the join table is new.

CREATE TABLE supplier_inventory (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id  INTEGER       NOT NULL,
    material_id  INTEGER       NOT NULL,
    quantity     NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    unit_price   NUMERIC(10, 2),
    CONSTRAINT uq_sup_inv UNIQUE (supplier_id, material_id),
    CONSTRAINT fk_sup_inv_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE,
    CONSTRAINT fk_sup_inv_material FOREIGN KEY (material_id) REFERENCES material  (id) ON DELETE CASCADE,
    CONSTRAINT chk_sup_inv_quantity CHECK (quantity >= 0)
);

CREATE INDEX idx_sup_inv_material ON supplier_inventory (material_id);
