-- Order history: persist every /api/calculate-order invocation, every alternative the
-- solver returned, and every user interaction (view/choose) so the team can analyse
-- which routes are actually picked and why.

CREATE TABLE customer_order (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID         NOT NULL UNIQUE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Requester: at least one of (app_user_id, telegram_chat_id) must be present.
    app_user_id           INTEGER,
    telegram_chat_id      BIGINT,
    source                VARCHAR(20)  NOT NULL,
    lang                  VARCHAR(8),

    -- Request snapshot (replay/audit).
    start_lat             NUMERIC(9, 6) NOT NULL,
    start_lng             NUMERIC(9, 6) NOT NULL,
    start_name            VARCHAR(255),
    destination_house_id  INTEGER,
    materials_json        JSONB        NOT NULL,

    -- Solver outcome summary (mirrors the shortest_distance / primary alternative).
    alternatives_count    INTEGER      NOT NULL,
    fully_fulfilled       BOOLEAN      NOT NULL,
    matrix_provider       VARCHAR(20)  NOT NULL,
    compute_ms            INTEGER      NOT NULL,

    -- Final user decision; filled in by /api/orders/{id}/choose.
    chosen_option_id      BIGINT,
    chosen_at             TIMESTAMPTZ,

    CONSTRAINT chk_order_source CHECK (source IN ('dashboard', 'telegram', 'api')),
    CONSTRAINT chk_order_requester CHECK (app_user_id IS NOT NULL OR telegram_chat_id IS NOT NULL),
    CONSTRAINT fk_order_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_order_dest_house FOREIGN KEY (destination_house_id) REFERENCES house (id) ON DELETE SET NULL
);

CREATE INDEX idx_order_created    ON customer_order (created_at DESC);
CREATE INDEX idx_order_user       ON customer_order (app_user_id, created_at DESC);
CREATE INDEX idx_order_dest_house ON customer_order (destination_house_id);
CREATE INDEX idx_order_telegram   ON customer_order (telegram_chat_id, created_at DESC);

CREATE TABLE order_route_option (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id              UUID        NOT NULL UNIQUE,
    order_id               BIGINT      NOT NULL,
    objective              VARCHAR(32) NOT NULL,
    is_primary             BOOLEAN     NOT NULL,
    sequence_index         INTEGER     NOT NULL,

    total_distance_km      INTEGER     NOT NULL,
    total_minutes          INTEGER     NOT NULL,
    total_stops            INTEGER     NOT NULL,
    supplier_stops_count   INTEGER     NOT NULL,
    fully_fulfilled        BOOLEAN     NOT NULL,

    house_ids_signature    TEXT        NOT NULL,
    maps_url               TEXT,
    payload_json           JSONB       NOT NULL,

    first_viewed_at        TIMESTAMPTZ,
    last_viewed_at         TIMESTAMPTZ,
    view_count             INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT uq_option_order_objective UNIQUE (order_id, objective),
    CONSTRAINT fk_option_order FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE
);

CREATE INDEX idx_option_order ON order_route_option (order_id);

-- Late-bound FK: customer_order.chosen_option_id references a row in order_route_option
-- created by the same calculate-order call. Declared after the table exists.
ALTER TABLE customer_order
    ADD CONSTRAINT fk_order_chosen_option
    FOREIGN KEY (chosen_option_id) REFERENCES order_route_option (id) ON DELETE SET NULL;

CREATE TABLE order_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL,
    option_id     BIGINT,
    event_type    VARCHAR(20) NOT NULL,
    at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    app_user_id   INTEGER,
    metadata_json JSONB,

    CONSTRAINT chk_event_type CHECK (event_type IN ('created', 'viewed', 'chosen', 'unchosen')),
    CONSTRAINT fk_event_order FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_option FOREIGN KEY (option_id) REFERENCES order_route_option (id) ON DELETE SET NULL,
    CONSTRAINT fk_event_user FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE INDEX idx_event_order ON order_event (order_id, at);
