-- Bitácora: append-only audit trail of who executed what.
-- Actor is polymorphic (dashboard app_user, crew-leader/worker, telegram chat) and is stored
-- as raw ids WITHOUT foreign keys plus a denormalized username/role snapshot, so rows keep
-- identifying the actor even after the user/worker row is deleted or renamed.

CREATE TABLE audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    actor_type       VARCHAR(16)  NOT NULL,
    app_user_id      INTEGER,
    worker_id        INTEGER,
    telegram_chat_id BIGINT,
    username         VARCHAR(255),          -- snapshot; for login_failure = attempted username
    role             VARCHAR(32),           -- snapshot of the role label at event time

    source           VARCHAR(16)  NOT NULL, -- 'api' | 'telegram'
    action           VARCHAR(32)  NOT NULL, -- create/update/delete/login_success/login_failure/...
    entity_type      VARCHAR(64),
    entity_id        VARCHAR(64),           -- text so it holds int ids AND order UUIDs

    http_method      VARCHAR(8),
    http_path        VARCHAR(512),
    http_status      INTEGER,
    client_ip        VARCHAR(45),
    request_id       VARCHAR(64),           -- joins audit rows to the access log

    details_json     JSONB,                 -- explicit-call payloads only (never request bodies)

    CONSTRAINT chk_audit_actor_type CHECK (actor_type IN ('app_user','worker','telegram','anonymous')),
    CONSTRAINT chk_audit_source     CHECK (source IN ('api','telegram'))
);

-- No CHECK on action: new endpoints must be auditable without a migration per verb.

CREATE INDEX idx_audit_at       ON audit_log (at DESC);
CREATE INDEX idx_audit_username ON audit_log (username, at DESC);
CREATE INDEX idx_audit_entity   ON audit_log (entity_type, at DESC);
CREATE INDEX idx_audit_action   ON audit_log (action, at DESC);

-- Append-only guard: rows never change once written. DELETE is intentionally not blocked so a
-- future retention-pruning migration stays possible; no API exposes it.
CREATE FUNCTION audit_log_no_update() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_log_no_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_no_update();
