-- Append-only log: captures every time a crew's status on a house stage changes.
-- Allows building a historical timeline of which crew worked which stage on which house and when.
CREATE TABLE house_stage_crew_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id     INTEGER      NOT NULL REFERENCES house(id) ON DELETE CASCADE,
    house_name   VARCHAR(255) NOT NULL,
    stage_order  INTEGER      NOT NULL,
    stage_name   VARCHAR(120) NOT NULL,
    stage_name_en VARCHAR(120),
    crew_id      INTEGER      REFERENCES crew(id) ON DELETE SET NULL,
    crew_name    VARCHAR(255),
    status       VARCHAR(30)  NOT NULL,
    start_date   DATE,
    end_date     DATE,
    logged_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_hscl_crew    ON house_stage_crew_log (crew_id, logged_at DESC);
CREATE INDEX idx_hscl_house   ON house_stage_crew_log (house_id, stage_order);

-- Backfill current assignments that are IN_PROGRESS or DONE
INSERT INTO house_stage_crew_log (house_id, house_name, stage_order, stage_name, stage_name_en, crew_id, crew_name, status, start_date, end_date, logged_at)
SELECT
    hs.house_id,
    h.name,
    hs.stage_order,
    hs.stage_name,
    hs.stage_name_en,
    hs.crew_id,
    c.name,
    hs.status,
    hs.start_date,
    hs.end_date,
    hs.updated_at
FROM house_stage hs
JOIN house h ON h.id = hs.house_id
LEFT JOIN crew c ON c.id = hs.crew_id
WHERE hs.crew_id IS NOT NULL
  AND hs.status IN ('IN_PROGRESS', 'DONE');
