-- Metadata for files held in the object bucket (Contabo, S3-compatible).
--
-- The bucket stores bytes; this table is the index. Postgres stays authoritative for structure, so
-- nothing in the app has to list the bucket to know what exists — and a rename in `doc_folder` does
-- not require copying objects, because `object_key` is fixed at upload time and never derived again.
--
-- Files hang off the existing `doc_folder` tree rather than off `house` directly: that tree already
-- has a node per house (`code = 'house_<id>'` under ACTIVE_SITES) with the 10-folder template, and
-- worker documents can hang under Administration & HR the same way. One mechanism, not two.
--
-- No `link_url` here: doc_document keeps holding external links (Google Drive), stored_object holds
-- files we own. A folder can show both, and one never silently becomes the other.

CREATE TABLE public.stored_object (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The only id the API exposes; the bigint never leaves the server (same rule as customer_order).
    public_id         uuid NOT NULL UNIQUE,
    -- Full key inside the bucket. Long because it carries the whole folder path.
    object_key        varchar(1024) NOT NULL UNIQUE,
    bucket            varchar(100)  NOT NULL,
    folder_id         integer       NOT NULL REFERENCES public.doc_folder(id) ON DELETE CASCADE,
    -- What the user called it. Kept apart from object_key, which is sanitised to ASCII.
    original_filename varchar(255)  NOT NULL,
    content_type      varchar(150),
    size_bytes        bigint        NOT NULL,
    etag              varchar(100),
    -- Username snapshot, not an FK: principals here can be app_user or worker, and audit_log is the
    -- one place allowed to resolve that mapping. Denormalised on purpose.
    uploaded_by       varchar(100),
    created_at        timestamp     NOT NULL DEFAULT now(),
    CONSTRAINT chk_stored_object_size CHECK (size_bytes >= 0)
);

-- The listing query: every file in one folder, newest first.
CREATE INDEX idx_stored_object_folder ON public.stored_object (folder_id, created_at DESC);

-- Prefix scans when a whole subtree is removed or re-synced.
CREATE INDEX idx_stored_object_key_prefix ON public.stored_object (object_key varchar_pattern_ops);
